# fly.toml app configuration file generated for open-ctp-server on 2024-08-25T23:50:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'open-ctp-server'
primary_region = 'atl'

[build]
[build.args]
GO_VERSION = '1.23.0'

[env]
PORT = '9000'

[http_service]
internal_port = 9000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[deploy]
strategy = "bluegreen"

[checks]
[checks.http]
type = "http"
port = 9000
interval = "10s"
timeout = "2s"
method = "GET"
path = "/health"
protocol = "http"
grace_period = "5s"
restart_limit = 0

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
