version: '3'

tasks:
  run:
    cmds:
      - echo Starting dev server...
      - air

  build:
    cmds: 
      - task protos
      - mkdir -p build_output
      - (cd src && go build -o ../build_output/open-ctp-server)

  test:
    cmds:
      - go test ./...

  test-coverage:
    cmds:
      - go test -cover ./...


  docs:
    cmds:
      - swag init # Regenerates docs according to the Swagger specs