version: '3'

tasks:
  run:
    cmds:
      - echo Starting dev server...
      - go run .

  build:
    cmds: 
      - task protos
      - mkdir -p build_output
      - (cd src && go build -o ../build_output/open-ctp-server)

  test:
    cmds:
      - go test ./...
  
  protos:
    cmds:
      - rm -rf proto_out
      - mkdir -p ./proto_out/cpp
      - mkdir -p ./proto_out/java
      - mkdir -p ./proto_out/csharp
      - mkdir -p ./proto_out/kotlin
      - mkdir -p ./proto_out/python
      - mkdir -p ./proto_out/go
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      # Compile all protobuffers to the output directory for distribution
      - find ./proto -name "*.proto" | xargs protoc --proto_path=./proto --cpp_out=./proto_out/cpp --java_out=./proto_out/java --csharp_out=./proto_out/csharp --go_out=./proto_out/go --python_out=./proto_out/python --kotlin_out=./proto_out/kotlin
      # Compile the Go gRPC definitions for use within the server
      - find ./proto -name "*.proto" | xargs protoc --proto_path=./proto --go-grpc_out=paths=source_relative:. --go_out=paths=source_relative:.