version: '3'

tasks:
  run:
    cmds:
      - echo Starting dev server...
      - go run .

  test:
    cmds:
      - go test
  
  protos:
    cmds:
      - protoc --proto_path=./proto --cpp_out=./proto_out/cpp ./proto/*.proto