// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "justinfarrellwebdev@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/create_account": {
            "post": {
                "description": "This endpoint creates a new multiplayer account, protected by a password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Create a new account",
                "parameters": [
                    {
                        "description": "account creation request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.CreateAccountArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Account successfully created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/game/create_game": {
            "post": {
                "description": "This endpoint creates a new multiplayer game, optionally protected by a password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Create a new game",
                "parameters": [
                    {
                        "description": "Game creation request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/game.CreateGameArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Game successfully created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the status of the service.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "account.Account": {
            "description": "Structure for representing a player account.",
            "type": "object",
            "properties": {
                "email": {
                    "description": "Email is the email address of the player.",
                    "type": "string"
                },
                "experience_level": {
                    "description": "ExperienceLevel represents the player's experience level (0=beginner, 1=easy, 2=medium, 3=hard, 4=very hard, 5=impossible)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/account.ExperienceLevel"
                        }
                    ]
                },
                "info": {
                    "description": "Info contains additional information about the player.",
                    "type": "string"
                },
                "location": {
                    "description": "Location indicates the player's real-life location.",
                    "type": "string"
                },
                "name": {
                    "description": "Name is the name of the player.",
                    "type": "string"
                }
            }
        },
        "account.CreateAccountArgs": {
            "description": "Structure for the account creation request payload.",
            "type": "object",
            "properties": {
                "account": {
                    "description": "The account to create.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/account.Account"
                        }
                    ]
                },
                "password": {
                    "description": "The password for the account to be created",
                    "type": "string"
                }
            }
        },
        "account.ExperienceLevel": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-varnames": [
                "Beginner",
                "Easy",
                "Medium",
                "Hard",
                "Very_Hard",
                "Impossible"
            ]
        },
        "game.CreateGameArgs": {
            "description": "Structure for the game creation request payload.",
            "type": "object",
            "properties": {
                "password": {
                    "description": "Password is the password for the game.\nThis field is required if PasswordProtected is true.\nIt must be longer than 6 characters.",
                    "type": "string"
                },
                "password_protected": {
                    "description": "PasswordProtected indicates whether the game is password-protected.\nIf true, a password must be provided.",
                    "type": "boolean"
                }
            }
        },
        "health.Response": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "OK"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Open Call to Power Server",
	Description:      "This is the open-source Call to Power and Call to Power 2 server project. This project is not sponsored, maintained or affiliated with Activision.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
