definitions:
  account.Account:
    description: Structure for representing a player account.
    properties:
      email:
        description: Email is the email address of the player.
        type: string
      experience_level:
        allOf:
        - $ref: '#/definitions/account.ExperienceLevel'
        description: ExperienceLevel represents the player's experience level (0=beginner,
          1=easy, 2=medium, 3=hard, 4=very hard, 5=impossible)
      info:
        description: Info contains additional information about the player.
        type: string
      location:
        description: Location indicates the player's real-life location.
        type: string
      name:
        description: Name is the name of the player.
        type: string
    type: object
  account.AccountParam:
    description: Structure for representing a player account with non-required fields.
    properties:
      email:
        description: Email is the email address of the player.
        type: string
      experience_level:
        allOf:
        - $ref: '#/definitions/account.ExperienceLevel'
        description: ExperienceLevel represents the player's experience level (0=beginner,
          1=easy, 2=medium, 3=hard, 4=very hard, 5=impossible)
      info:
        description: Info contains additional information about the player.
        type: string
      location:
        description: Location indicates the player's real-life location.
        type: string
      name:
        description: Name is the name of the player.
        type: string
    type: object
  account.CreateAccountArgs:
    description: Structure for the account creation request payload.
    properties:
      account:
        allOf:
        - $ref: '#/definitions/account.Account'
        description: The account to create.
      password:
        description: The password for the account to be created
        type: string
    type: object
  account.DeleteAccountArgs:
    description: Structure for the account deletion request payload.
    properties:
      account_id:
        description: The account ID for the account that will be deleted.
        type: integer
      session_id:
        description: A valid session ID for the account (so we know they are signed
          in)
        type: integer
    type: object
  account.ExperienceLevel:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    type: integer
    x-enum-varnames:
    - Beginner
    - Easy
    - Medium
    - Hard
    - Very_Hard
    - Impossible
  account.UpdateAccountArgs:
    description: Structure for the account update request payload.
    properties:
      account:
        allOf:
        - $ref: '#/definitions/account.AccountParam'
        description: The account to create.
      account_id:
        description: The account ID for the account that will be updated.
        type: integer
      password:
        description: The password for the account to be created
        type: string
      session_id:
        description: A valid session ID for the account (so we know they are signed
          in)
        type: integer
    type: object
  auth.Session:
    properties:
      account_id:
        type: integer
      created_at:
        type: string
      expires_at:
        type: string
      id:
        type: integer
    type: object
  game.CreateGameArgs:
    description: Structure for the game creation request payload.
    properties:
      password:
        description: |-
          Password is the password for the game.
          This field is required if PasswordProtected is true.
          It must be longer than 6 characters.
        type: string
      password_protected:
        description: |-
          PasswordProtected indicates whether the game is password-protected.
          If true, a password must be provided.
        type: boolean
    type: object
  health.Response:
    properties:
      status:
        example: OK
        type: string
    type: object
  lobby.CreateLobbyArgs:
    description: Structure for the lobby creation request payload.
    properties:
      lobby:
        allOf:
        - $ref: '#/definitions/lobby.Lobby'
        description: The lobby to create.
      password:
        description: |-
          FIXME make passwords actually get stored with lobbies
          The password for the lobby to be created
        type: string
    type: object
  lobby.DeleteLobbyArgs:
    description: Structure for the lobby deletion request payload.
    properties:
      lobby_id:
        description: The lobby ID for the lobby that will be deleted.
        type: integer
    type: object
  lobby.GetLobbyArgs:
    description: Structure for the lobby acquisition request payload.
    properties:
      lobby_id:
        description: The lobby ID for the lobby that will be retrieved.
        type: integer
    type: object
  lobby.Lobby:
    description: Structure for representing a player lobby.
    properties:
      id:
        description: ID is the unique identifier for the lobby.
        type: integer
      is_closed:
        description: IsClosed indicates if the lobby is closed.
        type: boolean
      is_muted:
        description: IsMuted indicates if the lobby is muted.
        type: boolean
      is_public:
        description: IsPublic indicates if the lobby is public.
        type: boolean
      name:
        description: Name is the name of the lobby.
        type: string
      owner_account_id:
        description: OwnerAccountId is the account ID of the lobby owner.
        type: string
      owner_name:
        description: OwnerName is the name of the lobby owner.
        type: string
    type: object
  lobby.LobbyParam:
    description: Structure for representing a player lobby with non-required fields.
    properties:
      id:
        description: ID is the unique identifier for the lobby.
        type: integer
      is_closed:
        description: IsClosed indicates if the lobby is closed.
        type: boolean
      is_muted:
        description: IsMuted indicates if the lobby is muted.
        type: boolean
      is_public:
        description: IsPublic indicates if the lobby is public.
        type: boolean
      name:
        description: Name is the name of the lobby.
        type: string
      owner_account_id:
        description: OwnerAccountId is the account ID of the lobby owner.
        type: string
      owner_name:
        description: OwnerName is the name of the lobby owner.
        type: string
    type: object
  lobby.UpdateLobbyArgs:
    description: Structure for the lobby update request payload.
    properties:
      lobby:
        allOf:
        - $ref: '#/definitions/lobby.LobbyParam'
        description: The lobby to update.
      lobby_id:
        description: The lobby ID for the lobby that will be updated.
        type: integer
    type: object
info:
  contact:
    email: justinfarrellwebdev@gmail.com
    name: API Support
  description: This is the open-source Call to Power and Call to Power 2 server project.
    This project is not sponsored, maintained or affiliated with Activision.
  title: Open Call to Power Server
paths:
  /account/create_account:
    post:
      consumes:
      - application/json
      description: This endpoint creates a new multiplayer account, protected by a
        password.
      parameters:
      - description: account creation request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/account.CreateAccountArgs'
      produces:
      - application/json
      responses:
        "201":
          description: Account successfully created
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "403":
          description: Forbidden
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create a new account
      tags:
      - account
  /account/delete_account:
    delete:
      consumes:
      - application/json
      description: This endpoint deletes a player account.
      parameters:
      - description: account deletion request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/account.DeleteAccountArgs'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted account!
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "403":
          description: Forbidden
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Deletes an account
      tags:
      - account
  /account/get_account:
    get:
      consumes:
      - application/json
      description: This endpoint gets a multiplayer account's info.
      parameters:
      - description: account ID
        in: query
        name: account_id
        required: true
        type: integer
      - description: session ID
        in: query
        name: session_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Account successfully retrieved
          schema:
            $ref: '#/definitions/account.Account'
        "400":
          description: Bad Request
          schema: {}
        "403":
          description: Forbidden
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Gets an account
      tags:
      - account
  /account/update_account:
    put:
      consumes:
      - application/json
      description: This endpoint updates an account's info.
      parameters:
      - description: account update request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/account.UpdateAccountArgs'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated account!
        "400":
          description: account_id must be specified
          schema:
            type: string
        "500":
          description: 'an error occurred while decoding the request body: <error
            message>'
          schema:
            type: string
      summary: Updates an account
      tags:
      - account
  /game/create_game:
    post:
      consumes:
      - application/json
      description: This endpoint creates a new multiplayer game, optionally protected
        by a password.
      parameters:
      - description: Game creation request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/game.CreateGameArgs'
      produces:
      - application/json
      responses:
        "201":
          description: Game successfully created
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create a new game
      tags:
      - game
  /health:
    get:
      consumes:
      - application/json
      description: Returns the status of the service.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.Response'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Health check endpoint
      tags:
      - health
  /lobby/create_lobby:
    post:
      consumes:
      - application/json
      description: This endpoint creates a new multiplayer lobby, protected by a password.
      parameters:
      - description: lobby creation request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/lobby.CreateLobbyArgs'
      produces:
      - application/json
      responses:
        "201":
          description: Lobby successfully created
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "403":
          description: Forbidden
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create a new lobby
      tags:
      - lobby
  /lobby/delete_lobby:
    delete:
      consumes:
      - application/json
      description: This endpoint deletes a multiplayer lobby.
      parameters:
      - description: lobby deletion request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/lobby.DeleteLobbyArgs'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted lobby!
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "403":
          description: Forbidden
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Deletes a lobby
      tags:
      - lobby
  /lobby/get_lobby:
    get:
      consumes:
      - application/json
      description: This endpoint gets a multiplayer lobby's info.
      parameters:
      - description: lobby acquisition request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/lobby.GetLobbyArgs'
      produces:
      - application/json
      responses:
        "200":
          description: Lobby successfully retrieved
          schema:
            $ref: '#/definitions/lobby.Lobby'
        "400":
          description: Bad Request
          schema: {}
        "403":
          description: Forbidden
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Gets a lobby
      tags:
      - lobby
  /lobby/update_lobby:
    put:
      consumes:
      - application/json
      description: This endpoint updates a lobby's info.
      parameters:
      - description: lobby update request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/lobby.UpdateLobbyArgs'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated lobby!
          schema:
            type: string
        "400":
          description: lobby_id must be specified
          schema:
            type: string
        "500":
          description: 'an error occurred while decoding the request body: <error
            message>'
          schema:
            type: string
      summary: Updates a lobby
      tags:
      - lobby
  /sessions:
    post:
      consumes:
      - application/json
      description: Create a new session for a user. Expires 12 hours from last interaction.
      parameters:
      - description: User ID
        in: body
        name: account_id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Session'
        "400":
          description: Bad Request
          schema: {}
      summary: Create a new session
      tags:
      - sessions
  /sessions/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a session by its ID
      parameters:
      - description: Session ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema: {}
      summary: Delete a session
      tags:
      - sessions
    get:
      consumes:
      - application/json
      description: Get a session by its ID
      parameters:
      - description: Session ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Session'
        "404":
          description: Not Found
          schema: {}
      summary: Get a session
      tags:
      - sessions
  /sessions/refresh/{account_id}:
    put:
      consumes:
      - application/json
      description: Refresh the session token for a given account ID. Extends the expiration
        by 12 hours.
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Session'
        "404":
          description: Not Found
          schema: {}
      summary: Refresh a session
      tags:
      - sessions
swagger: "2.0"
